<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <NoWarn />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <NoWarn />
  </PropertyGroup>

  <ItemGroup>
    <COMReference Include="WIA">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>94a0e92d-43c0-494e-ac29-fd45948a5221</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microvision.Types">
      <HintPath>C:\Program Files\Microvision Instruments\System\Reference Assemblies\400\Microvision.Types.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Data.SQLite">
      <HintPath>lib\System.Data.SQLite.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
