<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Company>Microvision Instruments</Company>
    <Trademark>$(Company) is a registered trademark.</Trademark>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
	<ProjectStartYear>1998</ProjectStartYear>
	<CopyrightYears Condition="'$(ProjectStartYear)' == '$([System.DateTime]::Now.Year)'">$(ProjectStartYear)</CopyrightYears>
	<CopyrightYears Condition="'$(ProjectStartYear)' != '$([System.DateTime]::Now.Year)'">$(ProjectStartYear)-$([System.DateTime]::Now.Year)</CopyrightYears>
    <Copyright>© $(CopyrightYears) by $(Company)</Copyright>
    <AssemblyTitle>$(MSBuildProjectName)</AssemblyTitle>
    <RootNamespace>$(MSBuildProjectName)</RootNamespace>
    <OutputType>Library</OutputType>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>MVLibs.snk</AssemblyOriginatorKeyFile>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
	<Product>Microvision Libraries 4.0</Product>
    <AssemblyVersion>14.0.0.0</AssemblyVersion>
    <FileVersion>14.0.0.0</FileVersion>
    <Version>14.0.0.0</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <NoWarn />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <NoWarn />
  </PropertyGroup>

  <ItemGroup>
    <COMReference Include="WIA">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>94a0e92d-43c0-494e-ac29-fd45948a5221</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Data.SQLite">
      <HintPath>lib\System.Data.SQLite.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microvision.Types\Microvision.Types.csproj" />
  </ItemGroup>

</Project>
