<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <Title>$(AssemblyName)</Title>
    <AssemblyTitle>$(MSBuildProjectName)</AssemblyTitle>
    <RootNamespace>$(MSBuildProjectName)</RootNamespace>
    <Authors>Microvision Instruments</Authors>
    <Company>Microvision Instruments</Company>
    <Product>Microvision Libraries 4.0</Product>
    <Description>Microvision OS Components</Description>
    <Copyright>© 1998-2026 by Microvision Instruments</Copyright>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <NoWarn />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <NoWarn />
  </PropertyGroup>

  <ItemGroup>
    <COMReference Include="WIA">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>94a0e92d-43c0-494e-ac29-fd45948a5221</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Data.SQLite">
      <HintPath>lib\System.Data.SQLite.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microvision.Types\Microvision.Types.csproj" />
  </ItemGroup>

</Project>
